# WARNING: do not modify this code, it is generated by _expression_select_gen.py.jinja2

from collections.abc import Mapping, Sequence
from datetime import datetime
from typing import (
    Any,
    TypeVar,
    overload,
)
from uuid import UUID

from sqlalchemy import (
    Column,
)
from sqlalchemy.sql.elements import (
    SQLCoreOperations,
)
from sqlalchemy.sql.roles import TypedColumnsClauseRole

from ._expression_select_cls import Select, SelectOfScalar

_T = TypeVar("_T")


_TCCA = TypedColumnsClauseRole[_T] | SQLCoreOperations[_T] | type[_T]

# Generated TypeVars start


_TScalar_0 = TypeVar(
    "_TScalar_0",
    Column,
    Sequence,
    Mapping,
    UUID,
    datetime,
    float,
    int,
    bool,
    bytes,
    str,
    None,
)

_T0 = TypeVar("_T0")


_TScalar_1 = TypeVar(
    "_TScalar_1",
    Column,
    Sequence,
    Mapping,
    UUID,
    datetime,
    float,
    int,
    bool,
    bytes,
    str,
    None,
)

_T1 = TypeVar("_T1")


_TScalar_2 = TypeVar(
    "_TScalar_2",
    Column,
    Sequence,
    Mapping,
    UUID,
    datetime,
    float,
    int,
    bool,
    bytes,
    str,
    None,
)

_T2 = TypeVar("_T2")


_TScalar_3 = TypeVar(
    "_TScalar_3",
    Column,
    Sequence,
    Mapping,
    UUID,
    datetime,
    float,
    int,
    bool,
    bytes,
    str,
    None,
)

_T3 = TypeVar("_T3")


# Generated TypeVars end


@overload
def select(__ent0: _TCCA[_T0]) -> SelectOfScalar[_T0]: ...


@overload
def select(__ent0: _TScalar_0) -> SelectOfScalar[_TScalar_0]: ...


# Generated overloads start


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
) -> Select[tuple[_T0, _T1]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
) -> Select[tuple[_T0, _TScalar_1]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
) -> Select[tuple[_TScalar_0, _T1]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
) -> Select[tuple[_TScalar_0, _TScalar_1]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
    _ent2: _TCCA[_T2],
) -> Select[tuple[_T0, _T1, _T2]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
    entity_2: _TScalar_2,
) -> Select[tuple[_T0, _T1, _TScalar_2]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
    _ent2: _TCCA[_T2],
) -> Select[tuple[_T0, _TScalar_1, _T2]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
    entity_2: _TScalar_2,
) -> Select[tuple[_T0, _TScalar_1, _TScalar_2]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
    _ent2: _TCCA[_T2],
) -> Select[tuple[_TScalar_0, _T1, _T2]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
    entity_2: _TScalar_2,
) -> Select[tuple[_TScalar_0, _T1, _TScalar_2]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
    _ent2: _TCCA[_T2],
) -> Select[tuple[_TScalar_0, _TScalar_1, _T2]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
    entity_2: _TScalar_2,
) -> Select[tuple[_TScalar_0, _TScalar_1, _TScalar_2]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
    _ent2: _TCCA[_T2],
    _ent3: _TCCA[_T3],
) -> Select[tuple[_T0, _T1, _T2, _T3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
    _ent2: _TCCA[_T2],
    entity_3: _TScalar_3,
) -> Select[tuple[_T0, _T1, _T2, _TScalar_3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
    entity_2: _TScalar_2,
    _ent3: _TCCA[_T3],
) -> Select[tuple[_T0, _T1, _TScalar_2, _T3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    _ent1: _TCCA[_T1],
    entity_2: _TScalar_2,
    entity_3: _TScalar_3,
) -> Select[tuple[_T0, _T1, _TScalar_2, _TScalar_3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
    _ent2: _TCCA[_T2],
    _ent3: _TCCA[_T3],
) -> Select[tuple[_T0, _TScalar_1, _T2, _T3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
    _ent2: _TCCA[_T2],
    entity_3: _TScalar_3,
) -> Select[tuple[_T0, _TScalar_1, _T2, _TScalar_3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
    entity_2: _TScalar_2,
    _ent3: _TCCA[_T3],
) -> Select[tuple[_T0, _TScalar_1, _TScalar_2, _T3]]: ...


@overload
def select(
    _ent0: _TCCA[_T0],
    entity_1: _TScalar_1,
    entity_2: _TScalar_2,
    entity_3: _TScalar_3,
) -> Select[tuple[_T0, _TScalar_1, _TScalar_2, _TScalar_3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
    _ent2: _TCCA[_T2],
    _ent3: _TCCA[_T3],
) -> Select[tuple[_TScalar_0, _T1, _T2, _T3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
    _ent2: _TCCA[_T2],
    entity_3: _TScalar_3,
) -> Select[tuple[_TScalar_0, _T1, _T2, _TScalar_3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
    entity_2: _TScalar_2,
    _ent3: _TCCA[_T3],
) -> Select[tuple[_TScalar_0, _T1, _TScalar_2, _T3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    _ent1: _TCCA[_T1],
    entity_2: _TScalar_2,
    entity_3: _TScalar_3,
) -> Select[tuple[_TScalar_0, _T1, _TScalar_2, _TScalar_3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
    _ent2: _TCCA[_T2],
    _ent3: _TCCA[_T3],
) -> Select[tuple[_TScalar_0, _TScalar_1, _T2, _T3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
    _ent2: _TCCA[_T2],
    entity_3: _TScalar_3,
) -> Select[tuple[_TScalar_0, _TScalar_1, _T2, _TScalar_3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
    entity_2: _TScalar_2,
    _ent3: _TCCA[_T3],
) -> Select[tuple[_TScalar_0, _TScalar_1, _TScalar_2, _T3]]: ...


@overload
def select(
    entity_0: _TScalar_0,
    entity_1: _TScalar_1,
    entity_2: _TScalar_2,
    entity_3: _TScalar_3,
) -> Select[tuple[_TScalar_0, _TScalar_1, _TScalar_2, _TScalar_3]]: ...


# Generated overloads end


def select(*entities: Any) -> Select | SelectOfScalar:
    if len(entities) == 1:
        return SelectOfScalar(*entities)
    return Select(*entities)
