"""init_db

Revision ID: 34abfb7ac266
Revises: 
Create Date:

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # (1)


# revision identifiers, used by Alembic.
revision = '34abfb7ac266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:  # (2)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',  # (3)
    sa.Column('id', sa.Integer(), nullable=False),  # (4)
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # (5)
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # (6)
    sa.Column('age', sa.Integer(), nullable=True),  # (7)
    sa.PrimaryKeyConstraint('id')  # (8)
    )
    # ### end Alembic commands ###


def downgrade() -> None:  # (9)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')  # (10)
    # ### end Alembic commands ###
